### ISSUE TITLE
Sonarr, Lidarr, & Prowlarr Theme Issues

### ISSUE THREAD

**Issue by 1ColdAssHonkey** [GilbN/theme.park#499] opened 2023-07-16 20:30 UTC
**Describe the bug**
In the past couple of days, the themes for Sonarr, Lidarr, and Prowlarr have been not completely working.  It appears that the devs changed some things on the back-end that effect Theme.Parks custom theming.  The themes should color the side bar and top bar, but are not.  Please see screenshots below.

**Theme Install Method** (Don't skip)
theme.park-init] Variables set:
PUID=99
PGID=100
TZ=America/Los_Angeles
TP_DOMAIN=TP_DOMAIN=10.10.20.49\/themepark
TP_URLBASE=

  - If using docker mods share your COMPLETE container logs..
[theme.park-init] Copying nginx files
[custom-init] No custom files found, skipping...
[theme.park-init] Copying theme files
[theme.park-init] Copying mods
[theme.park-init] Running themes.py and creating CSS files
[theme.park-init] done.
[ls.io-init] done.

- Stylus Config
None 

**Application Info** (Don't skip)
- Latest version
- ghcr.io/gilbn/theme.park:develop

**To Reproduce**
1. Load Web Browser
2. Go to local hosted version of Sonarr, Prowlarr, or Lidarr.

**Expected behavior**
The themes should cover and color the side bar and top bar, but are not. 
****Radarr** is still working** as it should.  Thought I surmise it might change soon.

**Screenshots**
![Lidarr](https://github.com/GilbN/theme.park/assets/66453120/0faee394-830b-4024-af0a-21eaa4a23966)
![Sonar](https://github.com/GilbN/theme.park/assets/66453120/82badd43-fa37-4b6f-bbb2-c86c01600296)
![Prowlarr](https://github.com/GilbN/theme.park/assets/66453120/9128f375-cd1d-43f1-8bc5-3c3b9018dfa9)

Still Working:
![Radarr](https://github.com/GilbN/theme.park/assets/66453120/46a92c2d-5486-4741-9ee6-035572e3d6aa)

**Desktop (If applicable) (please complete the following information):**
 - OS: Win10
 - Browser Firefox & Chrome/Brave

**Additional context**

**Comment by thatbritguy** [comment] 2023-07-17 14:18
Radarr and the unreleased one also not working on nightly.  Prowlarr, Lidarr, Readarr do work for me but those are on develop branch.  So it appears it is all current nightly builds that cause theme.park not to apply correctly.

**Comment by GilbN** [comment] 2023-07-17 15:37
@1ColdAssHonkey add some Application Info

**Comment by jpdsc** [comment] 2023-07-17 18:44
@GilbN my feedback:

Sonarr (latest v4):
4.0.0.565

Prowlarr (latest nightly):
1.7.3.3724

Radarr (latest nightly):
4.7.2.7654

**Comment by 1ColdAssHonkey** [comment] 2023-07-17 23:17
@GilbN 

I am using the nightly versions of each application.
Here are the current versions I have.

Sonarr:
    4.0.0.565-ls521 by [linuxserver.io](https://linuxserver.io/)

Radrr:
    4.7.1.7640-ls105 by [linuxserver.io](https://www.linuxserver.io/)

Lidarr:
    1.3.2.3377-ls87 by [linuxserver.io](https://www.linuxserver.io/) 

Prowlarr:
    1.7.3.3724-ls1 by [linuxserver.io](https://www.linuxserver.io/)

**Comment by GilbN** [comment] 2023-07-18 18:28
I've pushed some new tags on develop.
[prowlarr-testing](https://github.com/users/GilbN/packages/container/theme.park/110617272?tag=prowlarr-testing)

[lidarr-testing](https://github.com/users/GilbN/packages/container/theme.park/110617188?tag=lidarr-testing)

[sonarr-testing](https://github.com/users/GilbN/packages/container/theme.park/110617004?tag=sonarr-testing)

[radarr-testing](https://github.com/users/GilbN/packages/container/theme.park/110616835?tag=radarr-testing)

**Comment by GilbN** [comment] 2023-07-18 20:55
They're mods

**Comment by jpdsc** [comment] 2023-07-18 20:57
> They're mods

My bad, I see now that mods method is being used in this issue.
If you want me to test on non-mods let me know and I'm happy to help.

**Comment by thatbritguy** [comment] 2023-07-18 20:58
Will these work with the SWAG mod method? Using the testing branch.

**Comment by GilbN** [comment] 2023-07-18 20:59
Subfilter should not be affected. Only LSIO mods / hotio scripts

**Comment by jpdsc** [comment] 2023-07-18 21:03
> Subfilter should not be affected. Only LSIO mods / hotio scripts

Not sure if this reply was for me but I use subfilter and in Sonarr v4 the layout is broken.

**Comment by Majoraslayer** [comment] 2023-07-18 21:24
To throw in my two cents, I also ran into this issue today when I updated my Docker container for Prowlarr.  I'm also using the linuxserver container with subfilter.

![image](https://github.com/GilbN/theme.park/assets/95600737/b0ebfa74-fc74-49d1-819e-0b477bee47ab)

**Comment by GilbN** [comment] 2023-07-18 21:26
> > Subfilter should not be affected. Only LSIO mods / hotio scripts
> 
> Not sure if this reply was for me but I use subfilter and in Sonarr v4 the layout is broken. ![image](https://user-images.githubusercontent.com/7014736/254401731-01c010ae-d922-4768-9425-226c1497d473.png)

Guess we need to do the same fix on subfiltering.

Subfilter the body tag instead of the head tag.

```nginx
proxy_set_header Accept-Encoding "";
sub_filter
'<body>'
'<body><link rel="stylesheet" type="text/css" href="https://theme-park.dev/css/base/$app/$app-base.css">
<link rel="stylesheet" type="text/css" href="https://theme-park.dev/css/theme-options/$theme.css"></head>';
sub_filter_once on;
```

**Comment by GilbN** [comment] 2023-07-18 21:32
> To throw in my two cents, I also ran into this issue today when I updated my Docker container for Prowlarr. I'm also using the linuxserver container with subfilter.
> 

If you're using one of the default theme options and nothing custom you can easily switch to docker mods. 
`-e DOCKER_MODS=ghcr.io/gilbn/theme.park:prowlarr-testing`

**Comment by Majoraslayer** [comment] 2023-07-18 21:38
> > To throw in my two cents, I also ran into this issue today when I updated my Docker container for Prowlarr. I'm also using the linuxserver container with subfilter.
> 
> If you're using one of the default theme options and nothing custom you can easily switch to docker mods. `-e DOCKER_MODS=ghcr.io/gilbn/theme.park:prowlarr-testing` `-e TP_THEME=aquamarine`

That sorted mine out, thanks!

**Comment by jpdsc** [comment] 2023-07-18 21:39
> > > Subfilter should not be affected. Only LSIO mods / hotio scripts
> > 
> > 
> > Not sure if this reply was for me but I use subfilter and in Sonarr v4 the layout is broken.
> 
> Guess we need to do the same fix on subfiltering. Subfilter the body tag instead of the head tag.
> 
> ```nginx
> proxy_set_header Accept-Encoding "";
> sub_filter
> '<body>'
> '<body><link rel="stylesheet" type="text/css" href="https://theme-park.dev/css/base/$app/$app-base.css">
> <link rel="stylesheet" type="text/css" href="https://theme-park.dev/css/theme-options/$theme.css">';
> sub_filter_once on;
> ```

Tested with body tag, working as intended. Already had a snippet for Pi-hole so I could just re-use that one.

tp-snippet-body.conf
```
proxy_set_header Accept-Encoding "";
sub_filter
'</body>'
'<link rel="stylesheet" type="text/css" href="$url/css/base/$program/$theme.css">
</body>';
sub_filter_once on;
```

**Comment by thatbritguy** [comment] 2023-07-18 21:53
Changed from </head> to </body> in all my confs for the Starr apps and they are now properly themed again thanks.

**Comment by Majoraslayer** [comment] 2023-07-18 22:14
> > To throw in my two cents, I also ran into this issue today when I updated my Docker container for Prowlarr. I'm also using the linuxserver container with subfilter.
> 
> If you're using one of the default theme options and nothing custom you can easily switch to docker mods. `-e DOCKER_MODS=ghcr.io/gilbn/theme.park:prowlarr-testing` `-e TP_THEME=aquamarine`

I went through and added this to all of my Starr containers, but I'm having trouble getting it to work on Readarr for some reason.  I see a listing for Readarr in the Docker mods, so I'm not sure if there's something wrong with my syntax or what.  Below are my env variables and an example.  I believe this also has the now-revised subfilter applied to make sure one or the other should catch it.

```
  -e DOCKER_MODS=ghcr.io/gilbn/theme.park:readarr \
  -e TP_THEME=aquamarine
``` \

![image](https://github.com/GilbN/theme.park/assets/95600737/d53759b8-8024-4286-8c6a-a6a79dfcad56)

![image](https://github.com/GilbN/theme.park/assets/95600737/63cf0442-b9e3-435e-96b8-af89e54a6607)

**Comment by 1ColdAssHonkey** [comment] 2023-07-20 00:14
Thank you @GilbN, the testing themes worked like a charm!

Will you send out a notice when we can change the theme configs back to the normal ones?

**Comment by GilbN** [comment] 2023-07-21 16:06
Will try and make a release this weekend for all *arr mods

**Comment by GilbN** [comment] 2023-07-22 18:14
fixed on master

**Closed by GilbN** 2023-07-22 18:14 UTC
Labels: bug, invalid
