### ISSUE TITLE
Theme not working for newest radarr (3.1.1.4954-ls103)

### ISSUE THREAD

**Issue by mcpowell87** [GilbN/theme.park#190] opened 2021-05-05 02:20 UTC
**Describe the bug**
Just pulled the newest linuxserver docker image for Radarr (3.1.1.4954-ls103) and both the theme and 4k logo stopped working, and it is showing the default Radarr theming now.  I don't see any errors in the dev console or in the docker container logs.  I do see they slightly modified some styling, but it's so minor I'm not sure if that could really affect it.  I am using the Plex theme, but I tried others also and I get the same result.  

Any ideas?

**Comment by solongandthxforallthefish** [comment] 2021-05-05 07:41
same here, theme.park stopped working in newest radarr release

**Comment by GilbN** [comment] 2021-05-05 07:49
I'm not seeing this, I'm on the same version. Need more info. Please fill out the issue template.

**Comment by stefanelul2000** [comment] 2021-05-05 08:07
I'm running 3.1.1.4954 (latest version as of now) and the themes load without any issues.

**Comment by IntermittentlyRupert** [comment] 2021-05-05 10:19
I recently had to update the `DOCKER_MODS` environment variable from `gilbn/theme.park:<app>` to `ghcr.io/gilbn/theme.park:<app>` to fix this issue (for me it affected all containers using Docker mods). The GHCR URL is the version [now given in the docs](https://docs.theme-park.dev/setup/#enviroment-variables), but the Docker Hub version used to work fine as well.

Looking at the container logs when using the old URL, I see:

```
[cont-init.d] 10-adduser: exited 0.
[cont-init.d] 30-config: executing... 
[cont-init.d] 30-config: exited 0.
[cont-init.d] 99-custom-scripts: executing... 
[custom-init] no custom files found exiting...
[cont-init.d] 99-custom-scripts: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
```

...so it seems to not be pulling the mod correctly.

There might be an issue with the version deployed to Docker Hub, or maybe we're just running into rate limits? (Or something completely different that I haven't thought of.)

**Comment by solongandthxforallthefish** [comment] 2021-05-05 10:24
**Describe the bug**
thema park theme is not working since radarr Version 3.1.1.4954

**To Reproduce**
updated to Version 3.1.1.4954

**Expected behavior**
show the theme

**Theme Install Method**
Docker compose

```
version: '2.1'
services:
 radarr:
    image: ghcr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
        - PUID=1000
        - PGID=100
        - TZ=Europe/Amsterdam
        - DOCKER_MODS=gilbn/theme.park:radarr
        - TP_THEME=aquamarine
    volumes:
        - xxx:xxx
        - xxx:xxx
    ports:
        - 7878:7878
    restart: unless-stopped
```

**Comment by solongandthxforallthefish** [comment] 2021-05-05 10:29
its working with  `- DOCKER_MODS=ghcr.io/gilbn/theme.park:radarr`

**Comment by GilbN** [comment] 2021-05-05 10:34
Hm. Wierd, it did push to dockerhub https://github.com/GilbN/theme.park/runs/2482198482?check_suite_focus=true#step:5:247

**Comment by mcpowell87** [comment] 2021-05-05 13:18
I can confirm the theme and logo starts working for me when I update the URL to `- DOCKER_MODS=ghcr.io/gilbn/theme.park:radarr`

**Comment by GilbN** [comment] 2021-05-05 13:30
Do you guys see the same error in the container log when using dockerhub? 

```javascript
[mod-init] Attempting to run Docker Modification Logic
[mod-init] Applying gilbn/theme.park:sonarr files to container

gzip: stdin: not in gzip format
tar: Child returned status 1
tar: Error is not recoverable: exiting now

[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 01-envfile: executing...
[cont-init.d] 01-envfile: exited 0.
[cont-init.d] 10-adduser: executing...

-------------------------------------
_ ()
| | ___ _ __
| | / __| | | / \
| | \__ \ | | | () |
|_| |___/ |_| \__/


Brought to you by linuxserver.io
-------------------------------------
```

**Comment by mcpowell87** [comment] 2021-05-05 14:53
I actually do see that error when using the old url:

```
[mod-init] Attempting to run Docker Modification Logic
[mod-init] Applying gilbn/theme.park:radarr files to container

gzip: stdin: not in gzip format
tar: Child returned status 1
tar: Error is not recoverable: exiting now
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 01-envfile: executing...
[cont-init.d] 01-envfile: exited 0.
[cont-init.d] 10-adduser: executing...

-------------------------------------
          _         ()
         | |  ___   _    __
         | | / __| | |  /  \
         | | \__ \ | | | () |
         |_| |___/ |_|  \__/


Brought to you by linuxserver.io
-------------------------------------
```

But it's clean when changing the URL to `ghcr.io/gilbn/theme.park:radarr`
```
[mod-init] Attempting to run Docker Modification Logic
[mod-init] Applying gilbn/theme.park:radarr files to container
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 01-envfile: executing...
[cont-init.d] 01-envfile: exited 0.
[cont-init.d] 10-adduser: executing...

-------------------------------------
          _         ()
         | |  ___   _    __
         | | / __| | |  /  \
         | | \__ \ | | | () |
         |_| |___/ |_|  \__/


Brought to you by linuxserver.io
-------------------------------------
```

Now here's where things are weird: I mentioned earlier that I was able to reproduce this with Sonarr, but I switched back to the old url for sonarr (without ghcr.io) and it works now.  However, Radarr still does not work with the old url.

**Comment by GilbN** [comment] 2021-05-06 18:13
> I actually do see that error when using the old url:
> 
> ```
> [mod-init] Attempting to run Docker Modification Logic
> [mod-init] Applying gilbn/theme.park:radarr files to container
> 
> gzip: stdin: not in gzip format
> tar: Child returned status 1
> tar: Error is not recoverable: exiting now
> [s6-init] making user provided files available at /var/run/s6/etc...exited 0.
> [s6-init] ensuring user provided files have correct perms...exited 0.
> [fix-attrs.d] applying ownership & permissions fixes...
> [fix-attrs.d] done.
> [cont-init.d] executing container initialization scripts...
> [cont-init.d] 01-envfile: executing...
> [cont-init.d] 01-envfile: exited 0.
> [cont-init.d] 10-adduser: executing...
> 
> -------------------------------------
>           _         ()
>          | |  ___   _    __
>          | | / __| | |  /  \
>          | | \__ \ | | | () |
>          |_| |___/ |_|  \__/
> 
> 
> Brought to you by linuxserver.io
> -------------------------------------
> ```
> 
> But it's clean when changing the URL to `ghcr.io/gilbn/theme.park:radarr`
> 
> ```
> [mod-init] Attempting to run Docker Modification Logic
> [mod-init] Applying gilbn/theme.park:radarr files to container
> [s6-init] making user provided files available at /var/run/s6/etc...exited 0.
> [s6-init] ensuring user provided files have correct perms...exited 0.
> [fix-attrs.d] applying ownership & permissions fixes...
> [fix-attrs.d] done.
> [cont-init.d] executing container initialization scripts...
> [cont-init.d] 01-envfile: executing...
> [cont-init.d] 01-envfile: exited 0.
> [cont-init.d] 10-adduser: executing...
> 
> -------------------------------------
>           _         ()
>          | |  ___   _    __
>          | | / __| | |  /  \
>          | | \__ \ | | | () |
>          |_| |___/ |_|  \__/
> 
> 
> Brought to you by linuxserver.io
> -------------------------------------
> ```
> 
> Now here's where things are weird: I mentioned earlier that I was able to reproduce this with Sonarr, but I switched back to the old url for sonarr (without ghcr.io) and it works now. However, Radarr still does not work with the old url.

Hm. Still the same error for me on Sonarr.

**Comment by GilbN** [comment] 2021-05-07 19:29
> I'm seeing the same issue for deluge with both the old url and new url.
> 
> ```cs
> [mod-init] Attempting to run Docker Modification Logic
> [mod-init] Applying gilbn/theme.park:deluge files to container
> gzip: stdin: unexpected end of file
> tar: Child returned status 1
> tar: Error is not recoverable: exiting now
> [s6-init] making user provided files available at /var/run/s6/etc...exited 0.
> [s6-init] ensuring user provided files have correct perms...exited 0.
> [fix-attrs.d] applying ownership & permissions fixes...
> [fix-attrs.d] done.
> [cont-init.d] executing container initialization scripts...
> [cont-init.d] 01-envfile: executing... 
> [cont-init.d] 01-envfile: exited 0.
> [cont-init.d] 10-adduser: executing... 
> -------------------------------------
>           _         ()
>          | |  ___   _    __
>          | | / __| | |  /  \ 
>          | | \__ \ | | | () |
>          |_| |___/ |_|  \__/
> 
> 
> Brought to you by linuxserver.io
> -------------------------------------
> ```
> 
>  Edit - I was having the same problem with radarr and sonarr, but after "recreating" through portainer and toggling "pull latest image" they both started working correctly.
> _Unfortunately recreating & pulling the latest image for deluge did not work._

I just tested on deluge using ghcr.io and it works here.

**Comment by AugusDogus** [comment] 2021-05-07 19:33
> I just tested on deluge using ghcr.io and it works here.

Are there any troubleshooting steps I can follow to figure out why it's not working for me?

**Comment by GilbN** [comment] 2021-05-07 19:35
> > I just tested on deluge using ghcr.io and it works here.
> 
> Are there any troubleshooting steps I can follow to figure out why it's not working for me?

Got a docker run/compose you can share?

**Comment by AugusDogus** [comment] 2021-05-07 19:48
> Got a docker run/compose you can share?

Unfortunately not really. Most of containers for my Plex ecosystem were setup a long time ago using [plexguide](https://github.com/plexguide/PlexGuide.com) when I was still new to docker. 

I used [docker-autocompose](https://github.com/Red5d/docker-autocompose) to generate a docker-compose file from my container though. 

<details>
<summary>
docker-compose
</summary>

```docker

services:
  deluge:
    container_name: deluge
    entrypoint:
      - /init
    environment:
      - PUID=1000
      - PGID=1000
      - PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
      - HOME=/root
      - LANGUAGE=en_US.UTF-8
      - LANG=en_US.UTF-8
      - TERM=xterm
      - PYTHON_EGG_CACHE=/config/plugins/.python-eggs
      - DOCKER_MODS=ghcr.io/gilbn/theme.park:deluge
    hostname: 0341519d3303
    image: linuxserver/deluge:latest
    ipc: shareable
    labels:
      traefik.enable: true
      traefik.frontend.auth.forward.address: ""
      traefik.frontend.rule: Host:deluge.domain.com,
      traefik.port: 8112
    logging:
      driver: json-file
      options:
        max-file: 4
        max-size: 12m
    networks:
      - bridge
      - plexguide
    ports:
      - 0.0.0.0:8112:8112/tcp
      - 0.0.0.0:58846:58846/tcp
      - 0.0.0.0:58946:58946/tcp
    restart: unless-stopped
    volumes:
      - eff91dea4386fe13512f30c0a8febb4242fd4d9c45414742ff512e1b10c7f805:/downloads
      - /mnt:/mnt
      - /etc/localtime:/etc/localtime:ro
      - /opt/appdata/deluge:/config
version: "3"
networks:
  bridge:
    external: true
  plexguide:
    external: true
    
```
</summary>

**Comment by GilbN** [comment] 2021-05-07 23:30
This could be the issue with docker hub https://github.com/linuxserver/docker-baseimage-ubuntu/pull/69

**Comment by AugusDogus** [comment] 2021-05-09 19:06
After leaving it alone for ~3 hours I recreated the container through portainer and selected to pull latest image again. 
This time it worked just fine.
Might've had some weird caching issues going on.

**Comment by GilbN** [comment] 2021-05-10 21:01
This will be fixed when the fix trickles down to the different images. 
Using ghcr.io will work.

**Closed by GilbN** 2021-05-10 21:01 UTC
