### ISSUE TITLE
Traefik?

### ISSUE THREAD

**Issue by Mbarmem** [GilbN/theme.park#42] opened 2020-04-19 14:17 UTC
Hi,
Is their any way to install the theme via Traefik reverse proxy?

I am asking since i see guides for Apache and Caddy.

**Comment by gilbN** [comment] 2020-04-19 14:49
Hi. Sorry I haven't found a way to the subfiltering with træfik yet. I would as the dvs if they have some similar function. I use the better web server..nginx :P

**Comment by gilbN** [comment] 2020-09-11 23:24
@Mbarmem see if you can get this working https://pilot.traefik.io/plugins/270947800646156800/rewrite-body

**Comment by gilbN** [comment] 2020-10-21 21:23
Note to self: Doesn't work with the current implementation of the traefik plugin. 
https://github.com/traefik/plugin-rewritebody/issues/12

**Comment by IntermittentlyRupert** [comment] 2020-11-28 04:05
It seems that traefik/plugin-rewritebody#12 no longer causes issues with injecting styles. However traefik/plugin-rewritebody#13 causes the plugin to fail for some containers.

Of the containers I've tried, these work:
* `portainer/portainer`
* `plexinc/pms-docker`
* `linuxserver/jackett`
* `linuxserver/deluge`
* `linuxserver/nzbhydra2`

and these don't:
* `linuxserver/sonarr`
* `linuxserver/radarr`
* `linuxserver/sabnzbd`

Here's a minimal example for Portainer using the Docker config provider:
```yaml
version: "3"
services:
  traefik:
    image: traefik
    ports:
      - 80:80
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    command:
      - --providers.docker=true
      - --pilot.token=${TOKEN}
      - --experimental.plugins.rewrite.modulename=github.com/traefik/plugin-rewritebody
      - --experimental.plugins.rewrite.version=v0.3.1
  portainer:
    image: portainer/portainer
    labels:
      - traefik.http.routers.portainer.rule=Host(`portainer.localhost`)
      - traefik.http.routers.portainer.middlewares=portainer
      - traefik.http.middlewares.portainer.plugin.rewrite.rewrites.regex=</head>
      - traefik.http.middlewares.portainer.plugin.rewrite.rewrites.replacement=<link rel="stylesheet" type="text/css" href="https://gilbn.github.io/theme.park/CSS/themes/portainer/${THEME}.css"></head>
```

**Comment by gilbN** [comment] 2021-01-03 09:37
@IntermittentlyRupert btwm there are some docker mods you can now use to apply the themes with. (Only for linuxserver) https://github.com/gilbN/theme.park/wiki/Setup#docker-mods

**Comment by IntermittentlyRupert** [comment] 2021-01-11 00:26
@gilbN Oh, that's awesome! Between the Docker mods and the Traefik rewrite plugin, the only app I use that I can't inject styles for is Organizr, and that supports custom CSS.

**Comment by gilbN** [comment] 2021-01-11 08:06
> @gilbN Oh, that's awesome! Between the Docker mods and the Traefik rewrite plugin, the only app I use that I can't inject styles for is Organizr, and that supports custom CSS.

Yeah. I didnt crate any mods for apps that support custom css. And organizr has my themes in the marketplace too. 👍🏻

**Comment by beloso** [comment] 2021-02-11 17:47
Sorry for highjacking this. But do you have a rewrite example for Qbittorrent?

I was able to get the themes to working with Stylus + Middleware for the headers needed to hide.
I'd like to keep it all within the Middleswares

I tried this one:
```
  middlewares:
    qbittheme:
      plugin:
        rewritebody:
          rewrites:
            regex: </noscript>
            replacement: <link rel='stylesheet' type='text/css' href='https://gilbn.github.io/theme.park/CSS/themes/plex/organizr-dark.css'></noscript>
```

But no luck. Any help would be appreciated

For anyone wondering how to hide the headers with traefik, this is what I got.

```
http:
  middlewares:
    qbitheaders:
      headers:
        customRequestHeaders:
          X-Webkit-CSP: ""
          content-security-policy: ""
          X-Frame-Options: ""
        customResponseHeaders:
          X-Webkit-CSP: ""
          content-security-policy: ""
          X-Frame-Options: ""
```

**Comment by IntermittentlyRupert** [comment] 2021-02-11 23:40
@beloso If the rest of your Traefik config is working, my guess would be that this is probably caused by one of the plugin-rewritebody bugs from my earlier comment.

Your best bet would probably be to contribute a [Docker Mod](https://github.com/gilbN/theme.park/tree/docker-mods) for Qbittorrent and use that. They're a lot more stable and easier to work with than trying to get plugin-rewritebody to play nice.

**Comment by beloso** [comment] 2021-02-12 11:38
I researched a bit on doing a Mod, but I can't seem to find the default `index.html` for `qbittorrent`. It might be because I am not that well versed in how this is set up. If someone can point me in the right direction, I'd be happy to try my hand at this.

**Comment by gilbN** [comment] 2021-02-13 13:36
Yeah I didn't find the correct html file either.

**Comment by IntermittentlyRupert** [comment] 2021-02-13 23:52
I've opened #148 for this and added some additional notes.

**Comment by packruler** [comment] 2022-04-17 02:23
FYI I recently released a plugin that began as a fork of [traefik/plugin-rewritebody](https://github.com/traefik/plugin-rewritebody). It is now publicly available here: [packruler/rewrite-body](https://github.com/packruler/rewrite-body). 

Check out the [Examples](https://github.com/packruler/rewrite-body/wiki/Examples) page in the wiki for a quick example for implementation of the plugin.

**Comment by GilbN** [comment] 2022-04-17 09:12
Awesome! Thanks for creating this!

**Comment by beloso** [comment] 2022-04-17 10:10
I found that plug-in yesterday. I’ll give it a go this week.

**Comment by agneevX** [comment] 2022-04-17 16:41
@packruler Great plugin! Can you tell me how the dynamic env var works? Thanks.

**Comment by packruler** [comment] 2022-04-17 17:59
Yeah if you're using docker you can add `-e THEME=nord` to your `docker run traefik` command. I'm not sure exactly how to set it up in other environments at the moment but here's some more info on [Linux Environment Variables](https://phoenixnap.com/kb/linux-set-environment-variable).

**Comment by packruler** [comment] 2022-04-17 18:08
Actually I just found a better way to do it! At the top of your dynamic yaml definition you can add `# {{ $theme := "nord" }}` and then replace the `{{ env THEME }}` in the example with `{{ $theme }}`.  I'm going to update the wiki in project shortly and may have more things building on that 😁

**Comment by GilbN** [comment] 2022-04-22 15:12
I guess we can close this now? @packruler added some instructions here too: https://docs.theme-park.dev/setup/#traefik

**Comment by packruler** [comment] 2022-04-22 18:09
I have not heard of any issues yet.

**Closed** 2022-04-22 20:05 UTC
Labels: help wanted
